# title of website
title: 橙汁儿书签

# description of website
description: mr-licz's navigation site

# favicon of website
favicon: "https://github.com/mr-licz.png?size=40"

# your website url
url: https://mr-licz.github.io/bookmark/

# github profile url
github: "https://github.com/mr-licz"

# footer message
footer: © 2021-2023 @mr-licz

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: baidu
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 常用推荐
      sites:
        - name: 青柠味甜的博客
          description: 橙汁的资源分享平台碎碎念
          url: http://oranger.site/
        - name: 青柠味甜の中转站
          description: 橙汁的资源分享平台
          url: http://licz773.cccpan.com/
        - name: 阿虚同学
          description: 阿虚同学的万能百宝袋
          url: https://www.axutongxue.com/
        - name: Cnki
          description: 中国知网知识发现网络平台—面向海内外读者提供中国学术文献
          url: http://www.cnki.net/
        - name: bilibili
          description: 哔哩哔哩 (゜-゜)つロ 干杯~-bilibili
          url: https://www.bilibili.com/
        - name: 知乎
          description: 有问题，就会有答案。
          url: https://www.zhihu.com/
        - name: 豆瓣
          description: 提供图书、电影、音乐唱片的推荐、评论和价格比较，记录你的非凡生活
          url: https://www.douban.com/
        - name: 微信公众平台
          description: 再小的个体，也有自己的品牌
          url: https://mp.weixin.qq.com/
        - name: QQ邮箱
          description: 为亿万用户提供高效稳定便捷的电子邮箱服务
          url: https://mail.qq.com/
        - name: 阿里云盘
          description: 快速、不打扰、够安全、易于分享的个人网盘
          url: https://www.aliyundrive.com/drive
        - name: FlowUs
          description: FlowUs息流-新一代生产力工具
          url: https://flowus.cn/
        - name: Github
          description: 全球最大的同性交友平台
          url: https://github.com/
    - name: 学术科研
      sites:
        - name: Cnki
          description: 中国知网知识发现网络平台—面向海内外读者提供中国学术文献。
          url: http://www.cnki.net/
        - name: 万方数据
          description: 万方数据知识服务平台
          url: https://www.wanfangdata.com.cn/
        - name: 维普
          description: 中国期刊服务平台
          url: http://qikan.cqvip.com/
        - name: 学术搜索
          description: 聚合文献搜索-站在巨人的肩膀上
          url: https://scholar.chongbuluo.com/
        - name: 格桑花学术导航
          description: 聚合文献导航站-访问码2020
          url: http://www.20009.net/
        - name: 小鲸鱼文献
          description: 聚合文献搜索-知识就是力量
          url: http://www.9312.net/#/
        - name: 文献部落
          description: 一站式搞定文献下载-访问码2020
          url: http://459.org/
        - name: SCI-Hub网址链接
          description: SCI-Hub论文下载可用网址链接-实时更新
          url: https://tool.yovisun.com/scihub/
        - name: SCI-Hub 镜像1
          description: SCI-Hub 镜像网站1
          url: http://sci-hub.ee/
        - name: SCI-Hub 镜像2
          description: SCI-Hub 镜像网站2
          url: https://sci-hub.wf/
        - name: SCI-Hub 镜像3
          description: SCI-Hub 镜像网站3
          url: https://sci-hub.shop/
        - name: SCI-Hub 镜像4
          description: SCI-Hub 镜像网站4
          url: https://sci-hub.ren/
    - name: 专利检索
      sites:
        - name: 专利之星
          description: 专利检索系统
          url: https://cprs.patentstar.com.cn/
        - name: 专利查询（新）
          description: 国家知识产权局-中国及多国专利查询系统
          url: https://cpquery.cponline.cnipa.gov.cn/chinesepatent/index
        - name: 专利信息服务平台
          description: 知识产权出版社开发
          url: http://search.cnipr.com/
        - name: SooPAT专利搜索
          description: 
          url: http://www2.soopat.com/Home
        - name: innojoy
          description: 大为专利搜索引擎
          url: http://www.innojoy.com/search/index.html
        - name: Patentics
          description: 搜索全球专利
          url: https://www.patentics.com/searchcn.htm
        - name: Espacenet
          description: 欧洲专利数据库
          url: https://worldwide.espacenet.com/advancedSearch?locale=en_EP
        - name: 佰腾网
          description: 查专利，就上佰腾网
          url: https://www.baiten.cn/
        - name: 知嘟嘟
          description: 全球专利检索，就在知嘟嘟
          url: https://www.iprdb.com/
    - name: 电影搜索
      sites:
        - name: 热播之家
          description: 高清电视影视线。
          url: https://rebozj.pro/
        - name: Free OK
          description: 追剧也很卷。
          url: https://www.freeok.me/
        - name: 7080网
          description: 一个简单的影视搜索。
          url: https://7080.wang/
        - name: HDmoli
          description: 地址发布页https://molicp.com/
          url: https://www.hdmoli.com/
        - name: 茶杯狐
          description: 努力让找电影变得简单！
          url: https://cupfox.app
        - name: 电影狗搜索
          description: 专业电影搜索引擎
          url: https://www.dianyinggou.com/
        - name: 厂长资源
          description: 导航页https://czzy.site/，备用地址：czzyhd.com；czzy.pro；czzy.art；czzy.pw；czzy.fun；CZZY.TV；C-ZZY.COM；CZZY01.COM；CZZZU.COM；CZSPP.COM；czzz6.COM
          url: https://www.czzyhd.com/
        - name: BTNULL
          description: 原无名小站，备用线路改后缀为 to si nu in fun com
          url: https://www.btnull.org/
        - name: 低端影视
          description: 网址发布页https://ddys.site
          url: https://ddys.art/
        - name: BT世界
          description: 高清电影，美剧下载
          url: https://www.btsj6.com/
        - name: 孩提的世界
          description: 宫崎骏与久石让作品资源站
          url: https://share.ghibliwiki.org/
        - name: 6V电影网
          description: 地址发布页https://www.6v123.com/
          url: http://www.hao6v.cc/
        - name: 电影港
          description: 备用地址https://www.dygang.tv 地址发布页https://www.dygang.me/
          url: https://www.dygang.cc/
        - name: 555电影
          description: 备用地址555dyy1 更换为5 6 7 8
          url: https://www.555dyy1.com/
        - name: 雅图在线
          description: 
          url: http://www.yatu.tv:2082/
        - name: 在线之家
          description: 地址发布页https://www.zxzj.site/
          url: https://www.zxzjhd.com/
        - name: 注视影视
          description: 魁拔爱好者
          url: https://gaze.run/
        - name: 皮皮虾资源
          description: 含百度网盘、夸克、阿里云盘下载链接
          url: https://ppxzy.org/
        - name: 影巢
          description: 阿里云盘影视分享站
          url: https://www.hdhive.org/
        - name: 阿里云盘资源下载站
          description: 
          url: https://dianyingyuan.org/
    - name: 电影资讯
      sites:
        - name: 艺恩娱数
          description: 票房数据查询
          url: https://ys.endata.cn/DataMarket/Index
        - name: TMDB
          description: 电影数据库
          url: https://www.themoviedb.org/
        - name: 美剧日历
          description: 如名
          url: http://assrt.net/calendar
        - name: IMDB
          description: 国外的影视评分平台
          url: https://www.imdb.com/
        - name: 烂番茄
          description: 国外的影视评分平台
          url: https://www.rottentomatoes.com/
        - name: 字幕库
          description: 备用地址 https://zimuku.vip/ 永久备用zmk.pw
          url: hhttps://zimuku.org/
        - name: 射手网
          description: 字库下载老站
          url: https://assrt.net/
        - name: Anime字幕论坛
          description: 镜像https://404.website/
          url:  https://bbs.acgrip.com/
    - name: 软件下载
      sites:
        - name: 懒得勤快
          description: 互联网分享精神，勤于发现，乐于分享
          url: https://masuit.com/
        - name: 吾爱破解
          description:  LSG|安卓破解|病毒分析
          url: https://www.52pojie.cn
        - name: 小众软件
          description: 分享小众、实用、有趣、绿色的软件
          url: https://www.appinn.com/
        - name: 果核剥壳
          description: 互联网的净土
          url: https://www.ghxi.com/
        - name: 大眼仔旭
          description: 专注分享剪辑、解压、录屏、思维导图等办公资源分享
          url: http://www.dayanzai.me/
        - name: 423Down
          description: 个人运营的软件下载站博客
          url: https://www.423down.com/
        - name: 异次元软件
          description: 软件改变生活
          url: https://www.iplaysoft.com/
        - name: tuna
          description: 清华大学开源软件镜像站
          url: https://mirrors.tuna.tsinghua.edu.cn/
        - name: USTC
          description: 中科大开源软件镜像站
          url: http://mirrors.ustc.edu.cn/
        - name: SDUMIRRORS
          description: 山东大学镜像站
          url: https://mirrors.sdu.edu.cn/
        - name: 酷软清单
          description: 一个软件精选清单
          url: https://www.coolist.net/
        - name: Amazing Windows
          description: 精品软件收录项目
          url: https://amazing-apps.gitbook.io/windows-apps-that-amaze-us/zh-cn
        - name: 反斗限免
          description: 限时免费游戏资讯获取
          url: https://free.apprcn.com/
        - name: 老殁|殁漂遥
          description: 老殁专注分享12年
          url: https://www.mpyit.com/
        - name: FOSSHUB
          description: 英文软件站 Safe,Fast,and,Free
          url: https://www.fosshub.com/
        - name: Alternative
          description: 英文软件站
          url: https://alternativeto.net/
        - name: Digit77
          description: 主打Mac破解软件
          url: https://www.digit77.com/
        - name: 音速装机
          description: 装机软件推荐
          url: https://sonic.volf.club/
        - name: 阿萨姆软件
          description: 优质软件分享平台
          url: https://www.sssam.com/
        - name: دانلود رایگان نرم افزار
          description: 波斯于网站 maybe
          url: https://downloadly.ir/
        - name: 恩山无线论坛
          description: 路由器玩机论坛
          url: https://www.right.com.cn/FORUM/forum.php
    - name: 音乐在线
      sites:
        - name: MyFreeMP3
          description: 在线听歌、歌曲下载
          url: https://tool.liumingye.cn/music/
        - name: 音乐下载器
          description: 周杰伦歌曲在线、下载
          url: https://huan-xi.github.io/
        - name: mmplayer
          description: 高颜值在线播放站、结合IDM下载
          url: https://netease-music.fe-mm.com/#/music/playlist
        - name: myfreemp3
          description: 在线、下载
          url: https://myfreemp3juices.cc/
        - name: 铜钟
          description: 勉强可以用
          url: https://tonzhon.com/
        - name: MusicEnc
          description: 仅支持mp3格式
          url: https://www.musicenc.com/
        - name: 百乐米
          description: 分享好听稀有音乐
          url: https://bailemi.com/
        - name: Audio Mack
          description: 国外音乐站
          url: https://audiomack.com/
        - name: 麦田音乐网
          description: 用音乐和文字温暖生活
          url: https://www.mtyyw.com/
    - name: 云端网盘
      sites:
        - name: 阿里云盘
          description: 一款速度快、不打扰、够安全、易于分享的个人网盘
          url: https://www.aliyundrive.com/drive
        - name: 百度网盘
          description: 为您提供文件的网络备份、同步和分享服务
          url: https://pan.baidu.com/
        - name: 天翼云盘
          description: 中国电信推出的云存储服务，为用户提供跨平台的文件存储、备份、同步及分享服务
          url: https://cloud.189.cn/web/
        - name: TeraCloud
          description: 支持webav的日本免费网盘
          url: https://ise.teracloud.jp/browser/
        - name: 微云
          description: 通过微云 方便地在手机和电脑之间同步文件、推送照片和传输数据
          url: https://www.weiyun.com/
        - name: 超星云盘
          description: 超星学习通的网盘服务
          url: http://passport2.chaoxing.com/login?fid=&refer=http://i.mooc.chaoxing.com
        - name: 蓝奏云
          description: 天下武功，唯快不破!
          url: https://up.woozooo.com/
        - name: Yandex.disk
          description: 俄罗斯的网盘服务
          url: https://disk.yandex.com/client/disk
        - name: GoogleDrive
          description: 谷歌云盘
          url: https://drive.google.com/drive/my-drive
        - name: MEGA
          description: Sync your entire MEGA Cloud or selected folders with your computer
          url: https://mega.nz/start
        - name: 小米云服务
          description: 不是小米云盘哦
          url: https://i.mi.com/#/
        - name: pCloud
          description: The synchronization works absolutely perfectly on multiple Macs and iPads
          url: https://www.pcloud.com/zh/
        - name: 坚果云
          description: 一款便捷、安全的专业网盘产品，支持Webdav
          url: https://www.jianguoyun.com/
        - name: Dropbox
          description: Dropbox brings everything—traditional files, cloud content, and web shortcuts—together in one place
          url: https://www.dropbox.com/
        - name: Box
          description: Secure Cloud Content Management
          url: https://www.box.com/home
        - name: 中国移动云盘
          description: 中国移动推出的网盘服务
          url: https://yun.139.com/w/#/
        - name: 城通网盘
          description: The operation is simple and convenient, easy to understand, and supports mainstream platforms. 
          url: https://www.ctfile.com/
        - name: 牛奶快传
          description: 无需注册即可传输文件，上传下载不限速。
          url: https://cowtransfer.com/
        - name: 文叔叔
          description: 免费空间 40GB，一款永不限速的云存储产品。
          url: https://www.wenshushu.cn/
        - name: 115
          description: 115生活，一生相伴
          url: https://115.com/
        - name: 夸克网盘
          description: 为你带来极速体验
          url: https://pan.quark.cn/
        - name: 曲奇云盘
          description: 一款资源丰富,空间大,群组共享便捷的网盘
          url: https://www.quqi.com/
        - name: 永硕E盘
          description: 老牌网盘网站，网站式管理，无需软件
          url: http://licz773.ysepan.com/
    - name: 网盘搜索
      sites:
        - name: 万人迷吧
          description: 优质云盘搜索导航
          url: https://www.wanrenmi8.com/
        - name: UP云搜
          description: 阿里云盘资源搜索
          url: https://www.upyunso3.com/
        - name: 奈斯搜索
          description: 阿里云盘资源搜索
          url: https://www.niceso.fun/
        - name: 易搜
          description: 努力做最好用的云盘资源搜索引擎！
          url: https://yiso.fun/
        - name: 猫狸盘搜
          description: 阿里云盘资源搜索
          url: https://www.alipansou.com/
        - name: 阿里盘盘
          description: 论坛性质阿里云盘分享站
          url: https://www.panpanr.com/forum.php
        - name: 小纸条
          description: 开放纯粹的阿里云盘分享站
          url: https://ali.gitcafe.ink/
        - name: vpan
          description: 城通网盘资源分享站
          url: http://ct.vpan123.com/
    - name: 邮箱安全
      sites:
        - name: Gmail
          description: 谷歌邮箱
          url: https://mail.google.com/mail/u/0/#inbox
        - name: QQ邮箱
          description: 为亿万用户提供高效稳定便捷的电子邮箱服务
          url: https://mail.qq.com/cgi-bin/loginpage
        - name: 完美88邮箱
          description: 88后缀很完美
          url: https://www.88.com/
        - name: 傲游百变邮箱
          description: 影子邮箱，为邮箱安全保驾护航
    - name: 在线办公
      sites:
        - name: ALLtoALL
          description: 国内最全类型的在线文件转换平台，免费、快速，无须下载安装任何软件。
          url: https://www.alltoall.net/
        - name: office converter
          description: 转换音乐、视频、图像、PDF
          url: https://cn.office-converter.com/
        - name: CloudConvert
          description: support nearly all audio, video, document, ebook, archive, image, spreadsheet, and presentation formats.
          url: https://cloudconvert.com/
        - name: Convertio
          description: 文件转换器
          url: https://convertio.co/zh/
        - name: 小熊免费文件格式转换
          description: 免费在线转换Office文档,音视频文件,图像等各种文件格式
          url: https://www.ofoct.com/zh
        - name: ASS转SRT
          description: 字幕格式转换
          url: https://lab.sorz.org/tools/asstosrt/
        - name: FLACtoMP3
          description: 音乐格式转换
          url: https://www.flacmp3.net/online/
        - name: 迅捷视频
          description: 视频转换、视频编辑、音频转换、图片转换
          url: https://www.xunjieshipin.com/online-converter
        - name: Webpage to PDF
          description: 网页转PDF
          url: https://tools.pdf24.org/en/webpage-to-pdf
        - name: PDF解密去除限制
          description: PDF解密去限制、格式转换
          url: http://www.pdfdo.com/pdf-remove-restriction.aspx
        - name: ExtractPDF
          description: 从PDF文件中提取图像，文本和字体。
          url: https://www.extractpdf.com/
        - name: PDFcandy
          description: + 46多种在线PDF工具
          url: https://pdfcandy.com/cn/
        - name: 轻闪PDF
          description: 只需一步，便可解决PDF所有问题
          url: https://lightpdf.cn/
        - name: hiPDF
          description: Free All-In-One Online PDF Tool
          url: https://www.hipdf.com/
        - name: easyPDF
          description: 完全匿名的PDF转换器
          url: https://easypdf.com/cn
